### ISSUE TITLE
Allow setting content via slot

### ISSUE THREAD

**Issue by Azuka** [realdah/vue-blockui#1]
Would it be possible to allow setting the blockui's content using a slot? That way we can pass in html (e.g. a font-awesome spinning icon) as opposed to the attribute.

**Comment by realdah** [comment]
Let me add this option.

**Comment by realdah** [comment]
Hi Azuka, I have update the code to support embed html through the attribute.
The idea to use attribute instead of slot is that you don't have to create a Child Component just to add an animated CSS icon.

The usage is very simple (Please find updated readme document), and of course you need to include css and fonts properly into your application.

Please let me know if it works for your use case.

<img width="644" alt="sample2" src="https://user-images.githubusercontent.com/1226199/31450120-aaa9a142-ae76-11e7-9e1e-4324e29e2b54.png">

**Comment by Azuka** [comment]
Thanks @realdah. That was quick!
