### ISSUE TITLE
Do you have a demo project for using vue-blockui?

### ISSUE THREAD

**Issue by changxinw** [realdah/vue-blockui#2]
Really useful tool. But do you have a demo project for vue-blockui?

**Comment by realdah** [comment]
So far I did not create any demo site, just included the demo screens.
Thanks for asking, right now, the demo is nothing but a vue project created by vue-cli, then simply import vue-blockui and display it. So I did not publish it.

Because I provide the block-ui just as vue single file component, I have explained the trick part to config webpack support for [vue single file component](https://vuejs.org/v2/guide/single-file-components.html).

However, if you are using vue-cli to create your vue project which support vue single file component, then it is super straightforward, simply imported then start using it.

**Comment by changxinw** [comment]
Thanks!
