### ISSUE TITLE
Is it possible to block part of UI

### ISSUE THREAD

**Issue by o1lab** [realdah/vue-blockui#4]
<feature-request>

Is it possible to block UI for only one of the vue ui components in page. 

This can be parent html tag under which block-ui tag is placed.

This would be a really cool feature.

</feature-request>

**Comment by realdah** [comment]
it is possible through overriding the default css.

Please check below for class names that divs you might want to override.
https://github.com/realdah/vue-blockui#styling-customization

Steps:
1) put block ui component in the div where you want to block.
2) Make your parent div as **position: relative** 
3) override the block ui overlay from **position: fixed** to something like **position: absolute**.
See if it will work or not. you probably have to override more things, like using flex to center elements inside etc.


Anyway, there is a reason that I call this component **BlockUI** which is similar to jquery blockUI.  The reason is that this component will block the whole UI.
In your case, you probably want a loader component other than blockUI.

**Comment by o1lab** [comment]
@realdah Thank you for the details. I decided against blocking part of UI for a use case (for now). But I will refer to this in future.
